//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CAMBIOSDIVISAS
{
    public decimal IDCAMBIODIVISA { get; set; }
    public Nullable<decimal> IDMONEDAORIGEN { get; set; }
    public string MONEDAORIGEN { get; set; }
    public Nullable<decimal> IDMONEDADESTINO { get; set; }
    public string MONEDADESTINO { get; set; }
    public Nullable<double> VALOR { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
    public Nullable<System.DateTime> FECHATRM { get; set; }
    public Nullable<double> VALORTRM { get; set; }

    public virtual MONEDAS MONEDAS { get; set; }
    public virtual MONEDAS MONEDAS1 { get; set; }
}

public partial class CORREOS
{
    public decimal IDCORREO { get; set; }
    public Nullable<decimal> IDTIPOCORREO { get; set; }
    public string CORREO { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }

    public virtual TIPOCORREOS TIPOCORREOS { get; set; }
}

public partial class ESTADOSREFERENCIAS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ESTADOSREFERENCIAS()
    {
        this.REFERENCIASPAGOS = new HashSet<REFERENCIASPAGOS>();
    }

    public decimal IDESTADOREFERENCIA { get; set; }
    public string ESTADOREFERENCIA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<REFERENCIASPAGOS> REFERENCIASPAGOS { get; set; }
}

public partial class fed_facturas_enviadas
{
    public int fed_factura_enviada_id { get; set; }
    public decimal fed_num_factura { get; set; }
    public decimal fed_sucursal_id { get; set; }
    public string fed_factura_uuid { get; set; }
    public System.DateTime fed_fecha_registro { get; set; }
    public bool fed_consulta { get; set; }
}

public partial class fed_facturas_no_enviadas
{
    public int fed_factura_no_enviada_id { get; set; }
    public decimal fed_num_factura { get; set; }
    public decimal fed_sucursal_id { get; set; }
    public string fed_error { get; set; }
    public System.DateTime fed_fecha_registro { get; set; }
    public bool fed_resuelto { get; set; }
}

public partial class fed_facturas_procesadas
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public fed_facturas_procesadas()
    {
        this.fed_facturas_procesadas_errores = new HashSet<fed_facturas_procesadas_errores>();
    }

    public int id_factura_procesada { get; set; }
    public Nullable<decimal> num_factura { get; set; }
    public Nullable<decimal> sucursal { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public string mensaje_respuesta { get; set; }
    public Nullable<bool> registro_dian { get; set; }
    public Nullable<bool> correo_enviado { get; set; }
    public string correo_destinatarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<fed_facturas_procesadas_errores> fed_facturas_procesadas_errores { get; set; }
}

public partial class fed_facturas_procesadas_errores
{
    public int id_error_registrado { get; set; }
    public int id_factura_procesada { get; set; }
    public string error { get; set; }
    public bool error_dian { get; set; }
    public System.DateTime fecha_registro { get; set; }

    public virtual fed_facturas_procesadas fed_facturas_procesadas { get; set; }
}

public partial class fed_parametros
{
    public int fed_parametro_id { get; set; }
    public string fed_ruta_certificado { get; set; }
    public string fed_password_certificado { get; set; }
    public System.DateTime fed_fecha_consulta_inicial { get; set; }
    public string fed_ruta_documentos { get; set; }
    public string fed_ruta_pdfs { get; set; }
}

public partial class fed_resolucion_facturacion
{
    public int id_resolucion_facturacion { get; set; }
    public string numero_resolucion { get; set; }
    public string llave_tecnica { get; set; }
    public string prefijo { get; set; }
    public System.DateTime fecha_resolucion { get; set; }
    public System.DateTime resolucion_valida_desde { get; set; }
    public System.DateTime resolucion_valida_hasta { get; set; }
    public long resolucion_numero_desde { get; set; }
    public long resolucion_numero_hasta { get; set; }
    public Nullable<decimal> id_sucursal { get; set; }
}

public partial class fed_usuarios
{
    public int fed_usuario_id { get; set; }
    public string fed_usuario_email { get; set; }
    public string fed_usuario_login { get; set; }
    public string fed_usuario_password { get; set; }
    public int fed_usuario_intentos { get; set; }
    public bool fed_usuario_estado { get; set; }
    public System.DateTime fed_usuario_fecha { get; set; }
    public System.DateTime fed_usuario_fecha_ult_act { get; set; }
}

public partial class forward_clientes
{
    public string cli_codigo { get; set; }
    public string cli_descripcion { get; set; }
    public string cli_domicilio1 { get; set; }
    public string cli_domicilio2 { get; set; }
    public string cli_domicilio3 { get; set; }
    public string prv_codigo { get; set; }
    public string pai_codigo { get; set; }
    public string cli_telefono { get; set; }
    public string cli_fax { get; set; }
    public string cli_email { get; set; }
    public Nullable<decimal> iva_codigo { get; set; }
    public string cli_cuit { get; set; }
    public Nullable<bool> cli_retieneiva { get; set; }
    public string cli_contacto1 { get; set; }
    public string cli_contacto2 { get; set; }
    public string ven_codigo { get; set; }
    public string ven_codigo2 { get; set; }
    public string cli_condvta { get; set; }
    public Nullable<decimal> cli_ccfee { get; set; }
    public string div_ccfeemin { get; set; }
    public Nullable<decimal> cli_ccfeemin { get; set; }
    public string div_manejoa { get; set; }
    public Nullable<decimal> cli_manejo { get; set; }
    public string div_manejom { get; set; }
    public Nullable<decimal> cli_manejomar { get; set; }
    public string cli_dnitipo { get; set; }
    public string cli_dninumero { get; set; }
    public string cla_codigo { get; set; }
    public string cla_codigo2 { get; set; }
    public Nullable<decimal> cli_creditdias { get; set; }
    public Nullable<decimal> cli_creditmonto { get; set; }
    public Nullable<decimal> cli_creditdisponible { get; set; }
    public string cli_entrega1 { get; set; }
    public string cli_entrega2 { get; set; }
    public string cli_entrega3 { get; set; }
    public string cta_hai { get; set; }
    public Nullable<decimal> cta_auxiliar { get; set; }
    public Nullable<bool> cli_deshabilitado { get; set; }
    public string cli_historial { get; set; }
    public string des_codigo { get; set; }
    public Nullable<bool> cli_impdc { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public string usuario_id { get; set; }
    public string cli_willtrack { get; set; }
    public Nullable<decimal> cli_honopor { get; set; }
    public Nullable<decimal> cli_honomin { get; set; }
    public Nullable<decimal> gan_codigo { get; set; }
    public string CLI_ACTIVIDAD { get; set; }
    public string CLI_GTOSLOCALES { get; set; }
    public string CLI_GTOSAEREOS { get; set; }
    public string CLI_GTOSMARITIMOS { get; set; }
    public Nullable<bool> cli_nomanejoa { get; set; }
    public Nullable<bool> cli_nomanejom { get; set; }
    public Nullable<bool> cli_noccfee { get; set; }
    public Nullable<bool> desh_comercial { get; set; }
    public Nullable<bool> desh_operativo { get; set; }
    public Nullable<bool> desh_compras { get; set; }
    public Nullable<bool> desh_pagos { get; set; }
    public Nullable<bool> desh_ventas { get; set; }
    public Nullable<bool> desh_recibos { get; set; }
    public Nullable<bool> desh_listados { get; set; }
    public Nullable<decimal> PIB_CODIGO { get; set; }
    public Nullable<decimal> CLI_FREEDAYS { get; set; }
    public Nullable<bool> cli_rv_serv { get; set; }
    public Nullable<bool> cli_rv_ica { get; set; }
    public string cli_cpostal { get; set; }
    public Nullable<bool> cli_inscriptodgi { get; set; }
    public Nullable<System.DateTime> cli_fechadgi { get; set; }
    public Nullable<bool> cli_potencial { get; set; }
    public Nullable<decimal> cat_embarque { get; set; }
    public Nullable<decimal> cli_tarifa { get; set; }
    public Nullable<bool> cli_aproxima { get; set; }
    public Nullable<decimal> cli_tarifaRNG { get; set; }
    public Nullable<decimal> cli_cre_a { get; set; }
    public Nullable<decimal> cli_cre_m { get; set; }
    public string CURP { get; set; }
    public string cli_matriz { get; set; }
    public Nullable<bool> cli_sucursal { get; set; }
    public Nullable<System.DateTime> cli_credmaxfec { get; set; }
    public Nullable<decimal> ren_alicib { get; set; }
    public Nullable<System.DateTime> ren_venIB { get; set; }
    public Nullable<bool> cli_iss { get; set; }
    public Nullable<decimal> cli_iss_valor { get; set; }
    public Nullable<bool> cli_pis { get; set; }
    public Nullable<decimal> cli_pis_valor { get; set; }
    public Nullable<bool> cli_cofins { get; set; }
    public Nullable<decimal> cli_cofins_valor { get; set; }
    public Nullable<bool> cli_cssl { get; set; }
    public Nullable<decimal> cli_cssl_valor { get; set; }
    public Nullable<bool> cli_irrf { get; set; }
    public Nullable<bool> cli_irrf_obm { get; set; }
    public Nullable<bool> cli_iof { get; set; }
    public Nullable<decimal> cli_iof_valor { get; set; }
    public Nullable<bool> cli_cpmf { get; set; }
    public Nullable<bool> cli_aiss { get; set; }
    public Nullable<decimal> cli_aiss_valor { get; set; }
    public Nullable<bool> cli_apis { get; set; }
    public Nullable<decimal> cli_apis_valor { get; set; }
    public Nullable<bool> cli_apis_obm { get; set; }
    public Nullable<bool> cli_acofins { get; set; }
    public Nullable<decimal> cli_acofins_valor { get; set; }
    public Nullable<bool> cli_acofins_obm { get; set; }
    public Nullable<bool> cli_airrf { get; set; }
    public Nullable<decimal> cli_airrf_valor { get; set; }
    public Nullable<bool> cli_airrf_obm { get; set; }
    public Nullable<bool> cli_acssl { get; set; }
    public Nullable<decimal> cli_acssl_valor { get; set; }
    public Nullable<bool> cli_acssl_obm { get; set; }
    public Nullable<bool> cli_miss { get; set; }
    public Nullable<bool> cli_mpis { get; set; }
    public Nullable<decimal> cli_mpis_valor { get; set; }
    public Nullable<bool> cli_mpis_obm { get; set; }
    public Nullable<bool> cli_mcofins { get; set; }
    public Nullable<decimal> cli_mcofins_valor { get; set; }
    public Nullable<bool> cli_mcofins_obm { get; set; }
    public Nullable<bool> cli_mcssl { get; set; }
    public Nullable<decimal> cli_mcssl_valor { get; set; }
    public Nullable<bool> cli_mcssl_obm { get; set; }
    public Nullable<bool> cli_mirrf { get; set; }
    public Nullable<decimal> cli_mirrf_valor { get; set; }
    public Nullable<bool> cli_mirrf_obm { get; set; }
    public Nullable<bool> cli_mo { get; set; }
    public Nullable<decimal> cli_tc_em { get; set; }
    public Nullable<decimal> cli_tc_im { get; set; }
    public Nullable<decimal> cli_tc_ia { get; set; }
    public Nullable<decimal> cli_tc_ea { get; set; }
    public Nullable<decimal> cli_tc_de { get; set; }
    public Nullable<bool> CLI_ISSRETIDO { get; set; }
    public Nullable<decimal> cli_creddiasche { get; set; }
    public Nullable<bool> exc_iibb { get; set; }
    public Nullable<System.DateTime> exc_finiibb { get; set; }
    public string cli_codigojde { get; set; }
    public Nullable<decimal> cli_centavosadic { get; set; }
    public Nullable<System.DateTime> cli_cartagarantiaDesde { get; set; }
    public Nullable<System.DateTime> cli_cartagarantiaHasta { get; set; }
    public Nullable<bool> cli_cmpbloqueo { get; set; }
    public Nullable<decimal> cli_toleracmp { get; set; }
    public string cli_nombfantasia { get; set; }
    public Nullable<bool> cli_cheque { get; set; }
    public Nullable<bool> cli_deposito { get; set; }
    public string cli_banco { get; set; }
    public string cli_cuenta { get; set; }
    public string cli_agencia { get; set; }
    public string ent_datoadic1 { get; set; }
    public string ent_datoadic2 { get; set; }
    public string ent_datoadic3 { get; set; }
    public string ent_datoadic4 { get; set; }
    public string ent_datoadic5 { get; set; }
    public Nullable<int> cli_DAlertgascli { get; set; }
    public string ciu_codigo { get; set; }
    public string retib_numero { get; set; }
    public Nullable<decimal> cli_situacionib { get; set; }
    public Nullable<System.DateTime> fec_update { get; set; }
    public Nullable<bool> cli_ccxmail { get; set; }
    public string cli_bill_to { get; set; }
}

public partial class forward_ctacte
{
    public string cta_tipocli { get; set; }
    public string cta_cliente { get; set; }
    public string cta_tipo { get; set; }
    public string div_codigo { get; set; }
    public Nullable<System.DateTime> cta_fecha { get; set; }
    public string cta_comprobante { get; set; }
    public decimal cta_numero { get; set; }
    public string cta_cbteaplica { get; set; }
    public decimal cta_nroaplica { get; set; }
    public string cta_debehaber { get; set; }
    public decimal cta_aplicacion { get; set; }
    public Nullable<decimal> cta_importe { get; set; }
    public string cta_descripcion { get; set; }
    public Nullable<decimal> cot_divlocal { get; set; }
    public Nullable<decimal> cot_divotra { get; set; }
    public string fac_tipo { get; set; }
    public decimal fac_sucursal { get; set; }
    public Nullable<System.DateTime> cta_fechacont { get; set; }
    public Nullable<System.DateTime> cta_fecvto { get; set; }
    public Nullable<bool> cta_novedad { get; set; }
    public Nullable<decimal> rec_sucursal { get; set; }
    public Nullable<decimal> cta_paridad { get; set; }
    public string usuario_id { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public int recno { get; set; }
    public Nullable<decimal> cta_sucoper { get; set; }
    public Nullable<decimal> cta_saldo { get; set; }
    public Nullable<decimal> cta_sucfcapli { get; set; }
    public decimal cta_iva { get; set; }
    public decimal cta_flete { get; set; }
    public decimal cta_gravado { get; set; }
    public decimal cta_isr { get; set; }
    public decimal cta_derecho { get; set; }
    public decimal cta_retiva { get; set; }
    public decimal cta_exento { get; set; }
}

public partial class forward_factitem
{
    public string fac_tipo { get; set; }
    public decimal fac_sucursal { get; set; }
    public decimal fac_numero { get; set; }
    public string fac_comprobante { get; set; }
    public Nullable<decimal> gas_codigo { get; set; }
    public string fac_descripcion1 { get; set; }
    public string fac_descripcion2 { get; set; }
    public string fac_descripcion3 { get; set; }
    public string gas_tipo { get; set; }
    public Nullable<decimal> fac_impneto { get; set; }
    public Nullable<decimal> fac_imptotal { get; set; }
    public Nullable<decimal> fac_numoper { get; set; }
    public Nullable<decimal> fac_posicion { get; set; }
    public string fac_operacion { get; set; }
    public Nullable<bool> fac_agregado { get; set; }
    public Nullable<decimal> pre_numero { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public Nullable<decimal> nro_item { get; set; }
    public Nullable<decimal> fac_sucoper { get; set; }
    public int recno { get; set; }
    public string div_original { get; set; }
    public Nullable<decimal> fac_imporiginal { get; set; }
    public string fac_descripcion4 { get; set; }
    public string fac_descripcion5 { get; set; }
    public Nullable<decimal> fac_impneto2 { get; set; }
    public string con_numero { get; set; }
}

public partial class forward_facturas
{
    public string fac_tipo { get; set; }
    public decimal fac_sucursal { get; set; }
    public decimal fac_numero { get; set; }
    public string fac_comprobante { get; set; }
    public Nullable<System.DateTime> fac_fecha { get; set; }
    public string fac_tipocli { get; set; }
    public string fac_cliente { get; set; }
    public string fac_rsocial { get; set; }
    public string div_codigo { get; set; }
    public Nullable<decimal> iva_codigo { get; set; }
    public string fac_condvta { get; set; }
    public Nullable<System.DateTime> fac_fecvto { get; set; }
    public Nullable<decimal> fac_derecho { get; set; }
    public Nullable<decimal> fac_exento { get; set; }
    public Nullable<decimal> fac_gravado { get; set; }
    public Nullable<decimal> fac_iva { get; set; }
    public Nullable<decimal> fac_ivadif { get; set; }
    public Nullable<decimal> fac_subtotal { get; set; }
    public Nullable<decimal> fac_total { get; set; }
    public string fac_detalle1 { get; set; }
    public Nullable<decimal> cot_divlocal { get; set; }
    public Nullable<bool> fac_anulada { get; set; }
    public string fac_remito { get; set; }
    public Nullable<decimal> cot_divotra { get; set; }
    public Nullable<decimal> fac_anticipo { get; set; }
    public string fac_detalle2 { get; set; }
    public string fac_detalle3 { get; set; }
    public string fac_detalle4 { get; set; }
    public string fac_detalle5 { get; set; }
    public Nullable<decimal> fac_difcbiolocal { get; set; }
    public Nullable<decimal> fac_difcbiootra { get; set; }
    public string fac_tipoap { get; set; }
    public Nullable<decimal> fac_sucursalap { get; set; }
    public Nullable<decimal> fac_numeroap { get; set; }
    public string fac_comprobanteap { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public string usuario_id { get; set; }
    public Nullable<System.DateTime> fec_pase { get; set; }
    public Nullable<decimal> ots_statnro { get; set; }
    public Nullable<decimal> nro_int { get; set; }
    public Nullable<decimal> fac_paridad { get; set; }
    public Nullable<decimal> fac_sucoper { get; set; }
    public Nullable<bool> fac_CADIVI { get; set; }
    public int Recno { get; set; }
    public string ncf { get; set; }
    public string fac_subgrupo { get; set; }
    public Nullable<decimal> cot_divesp { get; set; }
    public string fac_informacionadic { get; set; }
    public Nullable<decimal> fac_cae { get; set; }
    public Nullable<System.DateTime> fac_vtocae { get; set; }
    public Nullable<decimal> fac_idcae { get; set; }
    public string fac_incoterm { get; set; }
    public Nullable<System.DateTime> fec_anu { get; set; }
    public string anu_usuario_id { get; set; }
    public Nullable<bool> fiscal_anulado { get; set; }
    public string fac_uuid { get; set; }
    public Nullable<decimal> TipoOperacion { get; set; }
    public Nullable<decimal> IDImpositivo { get; set; }
    public string Observaciones { get; set; }
    public string FormaPago { get; set; }
    public string Idioma { get; set; }
    public string fac_tipodeanulacion { get; set; }
    public bool asi_NoafectaNIIF { get; set; }
    public Nullable<bool> permiso_existente { get; set; }
    public string id_permiso_embarque { get; set; }
    public Nullable<decimal> destino_embarque { get; set; }
}

public partial class forward_recibos
{
    public decimal rop_numero { get; set; }
    public decimal rop_sucursal { get; set; }
    public Nullable<System.DateTime> rop_fecha { get; set; }
    public string rop_tipocliente { get; set; }
    public string rop_cliente { get; set; }
    public string rop_razonsocial { get; set; }
    public string div_codigo { get; set; }
    public Nullable<decimal> rop_total { get; set; }
    public string rop_concepto1 { get; set; }
    public string rop_concepto2 { get; set; }
    public Nullable<decimal> cot_divlocal { get; set; }
    public Nullable<decimal> cot_divotra { get; set; }
    public Nullable<bool> rop_anulado { get; set; }
    public Nullable<bool> rop_fccred { get; set; }
    public Nullable<bool> rop_credito { get; set; }
    public string rop_cuit { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public string usuario_id { get; set; }
    public Nullable<decimal> ots_statnro { get; set; }
    public int Recno { get; set; }
    public Nullable<System.DateTime> rop_fecdetracc { get; set; }
    public string rop_apunte { get; set; }
    public Nullable<System.DateTime> fec_anu { get; set; }
    public string anu_usuario_id { get; set; }
    public bool asi_NoafectaNIIF { get; set; }
}

public partial class INGRESOSPROPIOS
{
    public decimal IDINGRESOPROPIO { get; set; }
    public Nullable<decimal> CODIGO { get; set; }
    public string DESCRIPCION { get; set; }
    public string CTAVENTAS { get; set; }
    public string CTACOSTOS { get; set; }
}

public partial class MONEDAS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MONEDAS()
    {
        this.REFERENCIASPAGOS = new HashSet<REFERENCIASPAGOS>();
        this.CAMBIOSDIVISAS = new HashSet<CAMBIOSDIVISAS>();
        this.CAMBIOSDIVISAS1 = new HashSet<CAMBIOSDIVISAS>();
    }

    public decimal IDMONEDA { get; set; }
    public string MONEDA { get; set; }
    public string USUARIOCREA { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public string USUARIOMODIFICA { get; set; }
    public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
    public string ESTADO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<REFERENCIASPAGOS> REFERENCIASPAGOS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CAMBIOSDIVISAS> CAMBIOSDIVISAS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CAMBIOSDIVISAS> CAMBIOSDIVISAS1 { get; set; }
}

public partial class REFERENCIASPAGOS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public REFERENCIASPAGOS()
    {
        this.RELACIONDOCUMENTOS = new HashSet<RELACIONDOCUMENTOS>();
    }

    public decimal IDREFERENCIAPAGO { get; set; }
    public Nullable<decimal> IDUSUARIOWEB { get; set; }
    public Nullable<decimal> IDESTADOREFERENCIA { get; set; }
    public Nullable<decimal> IDMONEDA { get; set; }
    public Nullable<decimal> VALORREFERENCIA { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public Nullable<System.DateTime> FECHAPAGO { get; set; }
    public Nullable<decimal> VALORREPORTADOTC { get; set; }
    public string NUMEROTRANSACCIONTC { get; set; }
    public string METODOPAGO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RELACIONDOCUMENTOS> RELACIONDOCUMENTOS { get; set; }
    public virtual USUARIOSWEB USUARIOSWEB { get; set; }
    public virtual ESTADOSREFERENCIAS ESTADOSREFERENCIAS { get; set; }
    public virtual MONEDAS MONEDAS { get; set; }
}

public partial class RELACIONDOCUMENTOS
{
    public decimal IDRELACIONDOCUMENTO { get; set; }
    public Nullable<decimal> IDREFERENCIAPAGO { get; set; }
    public Nullable<decimal> IDTIPODOCUMENTO { get; set; }
    public string NUMERODOCUMENTO { get; set; }
    public Nullable<decimal> ICA { get; set; }
    public Nullable<decimal> RETEIVA { get; set; }
    public Nullable<decimal> VALORPAGO { get; set; }
    public Nullable<decimal> COTDIVISALOCAL { get; set; }
    public Nullable<decimal> COTDIVISAOTRA { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public Nullable<decimal> IDTIPORELACIONDOCUMENTO { get; set; }
    public string DETALLE { get; set; }
    public Nullable<int> SUCURSAL { get; set; }

    public virtual REFERENCIASPAGOS REFERENCIASPAGOS { get; set; }
    public virtual TIPORELACIONDOCUMENTOS TIPORELACIONDOCUMENTOS { get; set; }
}

public partial class TERCEROS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TERCEROS()
    {
        this.USUARIOSWEB = new HashSet<USUARIOSWEB>();
    }

    public decimal IDTERCERO { get; set; }
    public string DOCUMENTO { get; set; }
    public string RAZONSOCIAL { get; set; }
    public Nullable<decimal> IDTIPOTERCERO { get; set; }
    public string TIPOTERCERO { get; set; }
    public Nullable<decimal> IDPAIS { get; set; }
    public string PAIS { get; set; }
    public Nullable<decimal> IDCIUDAD { get; set; }
    public string CIUDADTERCERO { get; set; }
    public Nullable<decimal> IDSERVICIO { get; set; }
    public string SERVICIO { get; set; }
    public string DOCUMENTACIONCOMPLETA { get; set; }
    public Nullable<System.DateTime> FECHAENTREGA { get; set; }
    public string CERTIFICADOSDELACARGA { get; set; }
    public string CUALES { get; set; }
    public string PERMISOOPERAR { get; set; }
    public string DIRECCIONTERCERO { get; set; }
    public string TELEFONO { get; set; }
    public string TELEFONONOTIFICACION { get; set; }
    public string EMAIL { get; set; }
    public Nullable<decimal> IDFUNCIONARIOCOMERCIAL { get; set; }
    public string FUNCIONARIOCOMERCIAL { get; set; }
    public Nullable<decimal> IDFUNCIONARIOINSIDE { get; set; }
    public string FUNCIONARIOINSIDE { get; set; }
    public Nullable<decimal> IDFUNCIONARIOOPERATIVO { get; set; }
    public string FUNCIONARIOOPERATIVO { get; set; }
    public string CORREOFUNCIONARIOOPERATIVO { get; set; }
    public Nullable<System.DateTime> FECHACUMPLEAÑOS { get; set; }
    public string ESTADOBASICOS { get; set; }
    public Nullable<decimal> IDTIPOCUENTA { get; set; }
    public string TIPOCUENTA { get; set; }
    public string NOMBRESREPRESENTNATE { get; set; }
    public string EMAILREPRESENTANTE { get; set; }
    public string TELEFONOREPRESENTANTE { get; set; }
    public string CELULARREPRESENTANTE { get; set; }
    public string NUMEROCUENTATERCERO { get; set; }
    public Nullable<decimal> IDBANCOTERCERO { get; set; }
    public string BANCOCUENTATERCERO { get; set; }
    public string NOMBRESCONTACTO { get; set; }
    public string CARGOCONTACTO { get; set; }
    public string TELEFONOCONTACTO { get; set; }
    public Nullable<decimal> CELULARCONTACTO { get; set; }
    public string EMAILCONTACTO { get; set; }
    public string DIRECCIONCONTACTO { get; set; }
    public string TITULARCUENTA { get; set; }
    public Nullable<decimal> IDTIPOPERSONA { get; set; }
    public string TIPOPERSONA { get; set; }
    public Nullable<decimal> IDTIPOCONTRIBUYENTE { get; set; }
    public string TIPOCONTRIBUYENTE { get; set; }
    public string TIPOCLIENTE { get; set; }
    public string CLIENTETIPO { get; set; }
    public string CONTACTOCOMERCIOEXTERIOR { get; set; }
    public string TELEFONOCOMERCIOEXTERIOR { get; set; }
    public string CELULARCOMERCIOEXTERIOR { get; set; }
    public string EMAILCOMERCIOEXTERIOR { get; set; }
    public string ESTADOCOMERCIAL { get; set; }
    public string EMAILENVIOOFERTA1 { get; set; }
    public string EMAILENVIOOFERTA2 { get; set; }
    public string LLAMARALCLIENTE { get; set; }
    public Nullable<decimal> IDUSUARIOCOMERCIAL { get; set; }
    public string NOMBRESCOMERCIAL { get; set; }
    public Nullable<decimal> IDSUCURSALUSUARIOCOMERCIAL { get; set; }
    public string SUCURSALUSUARIOCOMERCIAL { get; set; }
    public Nullable<decimal> IDUSUARIOOPERATIVO { get; set; }
    public string NOMBRESOPERATIVO { get; set; }
    public Nullable<decimal> IDUSUARIOINSIDESALES { get; set; }
    public string NOMBRESINSIDESALES { get; set; }
    public string ENVIARCOTIZACION { get; set; }
    public string POLIZACONECGROUP { get; set; }
    public Nullable<System.DateTime> FECHAVIGENCIAECGROUP { get; set; }
    public string POLIZAGLOBAL { get; set; }
    public Nullable<System.DateTime> FECHAVIGENCIAGLOBAL { get; set; }
    public string OTORGAEXONERACION { get; set; }
    public string RUTASEXONERACION { get; set; }
    public string EXONERACIONDROPOFF { get; set; }
    public string RUTASDROPOFF { get; set; }
    public string CARGASTRANSITORIAS { get; set; }
    public string DIASLIBRES { get; set; }
    public string CARGASBLS { get; set; }
    public string TIPOBLS { get; set; }
    public string DESCARGUEDIRECTO { get; set; }
    public string QUIENTRASLADA { get; set; }
    public string QUIENRECIBE { get; set; }
    public string DEPOSITOTRASLADO { get; set; }
    public string OBERVACIONESCOMERCIALES { get; set; }
    public string RECIBIRESTATUSOPERATIVOS { get; set; }
    public string MEDIORECIBIRESTATUS { get; set; }
    public string LLAMARCONFIRMAR { get; set; }
    public string CADACUANTOLLAMAR { get; set; }
    public string EMAILNOTIFICACION { get; set; }
    public string COMOFACTURAROPERATIVOS { get; set; }
    public string TIEMPOGENERARFACTURA { get; set; }
    public string CONTACTOAGENCIAADUANA { get; set; }
    public string EMAILAGENCIA { get; set; }
    public string TELEFONOAGENCIA { get; set; }
    public string CELULARAGENCIA { get; set; }
    public string OBSERVACIONESOPERATIVOS { get; set; }
    public string NACIONALIZACION { get; set; }
    public string ESPEFICIQUEOTRANACIONALIZACION { get; set; }
    public string RECIBIRESTATUSADUANA { get; set; }
    public string COMOFACTURARADUANA { get; set; }
    public string DESCUENTOSLEGALES { get; set; }
    public string ESPECIFIQUEDESCUENTO { get; set; }
    public Nullable<System.DateTime> FECHAVECIMIENTOPODER { get; set; }
    public string PUERTOCIUDADES { get; set; }
    public string SOLICITUDANTICIPO { get; set; }
    public string TIPOPRODUCTO { get; set; }
    public string MODOPAGOIMPUESTO { get; set; }
    public string CONDICIONESRETIRO { get; set; }
    public string FORMATOVALORACION { get; set; }
    public string INSPECCIONPREVIA { get; set; }
    public string TIENECREDITO { get; set; }
    public string CONDICIONESESPECIALES { get; set; }
    public string OBSERVACIONESADUANA { get; set; }
    public Nullable<System.DateTime> FECHACIERREFACTURACION { get; set; }
    public string DIRECCIONRADICARFACTURAS { get; set; }
    public string PAISRADICARFACTURA { get; set; }
    public string CIUDADRADICARFACTURA { get; set; }
    public string NOMBRESCONTACTOPAGOS { get; set; }
    public string TELEFONOCONTACTOPAGOS { get; set; }
    public string CELULARCONTACTOPAGOS { get; set; }
    public string EMAILCONTACTOPAGOS { get; set; }
    public string CUENTACONCREDITO { get; set; }
    public string DIASCREDITO { get; set; }
    public string LIBERACIONAUTOMATICA { get; set; }
    public string DIASLIBERACION { get; set; }
    public string PAGARAENCOLOMBIA { get; set; }
    public string MONEDAFACTURAR { get; set; }
    public string PUNTOSTRM { get; set; }
    public string NOMBRESTESORERIA { get; set; }
    public string TELEFONOTESORERIA { get; set; }
    public string EXTENSIONTESORERIA { get; set; }
    public Nullable<System.DateTime> FECHAPAGOTESORERIA { get; set; }
    public string OBSERVACIONESADMINISTRATIVAS { get; set; }
    public string EMAILCARTERA { get; set; }
    public string MUESTRADOLARES { get; set; }
    public string ADJUNTO { get; set; }
    public Nullable<decimal> IDSUCURSAL { get; set; }
    public string SUCURSALOPERATIVA { get; set; }
    public string SUCURSAL { get; set; }
    public string COTIZACIONSEGURO { get; set; }
    public string RECONOCIMIENTOMERCANCIA { get; set; }
    public string CONTACTOENPUERTO { get; set; }
    public string TELEFONOCONTACTOENPUERTO { get; set; }
    public string EMPRESADETRANSPORTETERRRESTRE { get; set; }
    public Nullable<System.DateTime> FECHAASIGNACIONCOMERCIAL { get; set; }
    public Nullable<System.DateTime> FECHAASIGNACIONINSIDE { get; set; }
    public Nullable<System.DateTime> FECHAASIGNACIONOPERATIVO { get; set; }
    public string TELEFONOEXCEPCIONES { get; set; }
    public string MANEJOEXCEPCIONES { get; set; }
    public string CONFIRMACIONRECIBIDOINFORMACION { get; set; }
    public string NOMBREDEQUIENRECIBE { get; set; }
    public Nullable<System.DateTime> FECHAENTREGAFACTURACION { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public Nullable<decimal> IDUSUARIOCREA { get; set; }
    public string USUARIOCREA { get; set; }
    public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
    public Nullable<decimal> IDUSUARIOMODIFICA { get; set; }
    public string USUARIOMODIFICA { get; set; }
    public string DIGITOVERIFICACION { get; set; }
    public string SECTORECONOMICO { get; set; }
    public string PRODUCTOSMANEJADOS { get; set; }
    public Nullable<decimal> IDSECTORECONOMICO { get; set; }
    public string NOMBRESECTOR { get; set; }
    public string PERMISOCOMERCIAL { get; set; }
    public string PERMISOOPERATIVO { get; set; }
    public string PERMISOFACTURACION { get; set; }
    public string PERMISORECIBOS { get; set; }
    public string PERMISOCOMPRAS { get; set; }
    public string PERMISOPAGOS { get; set; }
    public string PERMISOLISTACLTES { get; set; }
    public Nullable<decimal> MONTODECREDITO { get; set; }
    public Nullable<decimal> CATDEEMBARQUE { get; set; }
    public string INSIDE { get; set; }
    public string COMERCIAL { get; set; }
    public Nullable<decimal> ESTADOSFINANCIEROS { get; set; }
    public Nullable<decimal> DOCUMENTOSVINCULACION { get; set; }
    public Nullable<decimal> VERACIDADINFORMACION { get; set; }
    public Nullable<decimal> IDCOMMODITY { get; set; }
    public string CODIGOCOMMODITY { get; set; }
    public string DESCRIPCIONCOMMODITY { get; set; }
    public Nullable<decimal> COMMODITY { get; set; }
    public Nullable<decimal> VERIFICACIONLSTAS { get; set; }
    public Nullable<decimal> PONDERACION { get; set; }
    public string CRITICIDADCLIENTE { get; set; }
    public Nullable<decimal> IDCRITICIDADCLIENTE { get; set; }
    public Nullable<decimal> IDSECTORECONOMICOTERCERO { get; set; }
    public Nullable<System.DateTime> FECHACREACIONCLIENTE { get; set; }
    public string OBSERVACIONESFINANCIEROS { get; set; }
    public string OBSERVACIONESDOCUMENTOS { get; set; }
    public string OBSERVACIONESINFORMACION { get; set; }
    public string OBSERVACIONESCOMMODITY { get; set; }
    public string OBSERVACIONESLISTAS { get; set; }
    public Nullable<decimal> IDAGENCIASADUANAS { get; set; }
    public string NOMBREAGENCIAADUANA { get; set; }
    public Nullable<System.DateTime> FECHAACTUALIZACIONCREDITO { get; set; }
    public Nullable<System.DateTime> FECHAVENCIMIENTOCREDITO { get; set; }
    public Nullable<System.DateTime> FECHAACTUAL { get; set; }
    public string COMOFACTURARCLIENTE { get; set; }
    public string CLIENTEHABILITADOOPERAR { get; set; }
    public Nullable<decimal> VENTASANUALES { get; set; }
    public Nullable<decimal> VENTASCREDITO { get; set; }
    public Nullable<decimal> CUENTASPORCOBRARPROMEDIO { get; set; }
    public Nullable<decimal> CUENTASPORPAGARPROMEDIO { get; set; }
    public Nullable<decimal> COMPRAS { get; set; }
    public Nullable<decimal> COSTOSDEVENTAPERIODO { get; set; }
    public Nullable<decimal> INVENTARIOPROMEDIO { get; set; }
    public Nullable<decimal> ACTIVOTOTAL { get; set; }
    public Nullable<decimal> PASIVOCORRIENTE { get; set; }
    public Nullable<decimal> PASIVOTOTAL { get; set; }
    public Nullable<decimal> OBLIGACIONESFINANCIERAS { get; set; }
    public Nullable<decimal> ACTIVOCORRIENTE { get; set; }
    public Nullable<decimal> CAPITALCONTABLE { get; set; }
    public Nullable<decimal> ACTIVOFIJOBRUTO { get; set; }
    public Nullable<decimal> UTILIDADBRUTA { get; set; }
    public Nullable<decimal> UTILIDADOPERACIONAL { get; set; }
    public Nullable<decimal> UTILIDADESACUMULADAS { get; set; }
    public Nullable<decimal> VENTASPROMEDIODIARIAS { get; set; }
    public Nullable<decimal> ROTACIONDECARTERA { get; set; }
    public Nullable<decimal> PERIODOPROMEDIODECOBRO { get; set; }
    public Nullable<decimal> ROTACIONDECUENTASPORPAGAR { get; set; }
    public Nullable<decimal> ROTACIONDEINVETARIOVECES { get; set; }
    public Nullable<decimal> ROTACIONDEINVENTARIODIAS { get; set; }
    public Nullable<decimal> ENDEUDAMIENTO { get; set; }
    public Nullable<decimal> ENDEUDAMIENTOCORTOPLAZO { get; set; }
    public Nullable<decimal> ENDEUDAMIENTODINANCIERO { get; set; }
    public Nullable<decimal> RAZONCORRIENTE { get; set; }
    public Nullable<decimal> RAZONDEPROTECCIONALPASIVOTOTAL { get; set; }
    public Nullable<decimal> ROTACIONDEACTIVOSFIJOS { get; set; }
    public Nullable<decimal> MARGENBRUTOUTILIDADORENTABILIDAD { get; set; }
    public Nullable<decimal> MARGENOPERACIONALDEUTILIDAD { get; set; }
    public Nullable<decimal> X1 { get; set; }
    public Nullable<decimal> X2 { get; set; }
    public Nullable<decimal> X3 { get; set; }
    public Nullable<decimal> X4 { get; set; }
    public Nullable<decimal> X5 { get; set; }
    public Nullable<decimal> INDICADORPONDERACIONX1 { get; set; }
    public Nullable<decimal> INDICADORPONDERACIONX2 { get; set; }
    public Nullable<decimal> INDICADORPONDERACIONX3 { get; set; }
    public Nullable<decimal> INDICADORPONDERACIONX4 { get; set; }
    public Nullable<decimal> INDICADORPONDERACIONX5 { get; set; }
    public Nullable<decimal> MEDIDADRENDIMIENTOX1 { get; set; }
    public Nullable<decimal> MEDIDADRENDIMIENTOX2 { get; set; }
    public Nullable<decimal> MEDIDADRENDIMIENTOX3 { get; set; }
    public Nullable<decimal> MEDIDADRENDIMIENTOX4 { get; set; }
    public Nullable<decimal> MEDIDADRENDIMIENTOX5 { get; set; }
    public Nullable<decimal> PUNTAEGLOBAL { get; set; }
    public string NOMBRECALIFICACIONESTUDIO { get; set; }
    public Nullable<decimal> IDCRITERIOCRITICIDADESTUDIO { get; set; }
    public Nullable<decimal> DIASLIBRESNORMAL { get; set; }
    public Nullable<decimal> DIASLIBRESESPECIAL { get; set; }
    public Nullable<decimal> COBROMORA { get; set; }
    public string CIUDADFRECUENTE { get; set; }
    public string ESTADORUTA { get; set; }
    public string PERMISOMODULOCOTIZACION { get; set; }
    public string PERMISOMODULOSHIPPING { get; set; }
    public string PERMISOMODULOFACTURACION { get; set; }
    public string ESTADOASIGNACION { get; set; }
    public Nullable<System.DateTime> FECHAASIGNACION { get; set; }
    public string CLIENTERO { get; set; }
    public string SUCBOGOTA { get; set; }
    public string SUCCALI { get; set; }
    public string SUCMEDEILLN { get; set; }
    public string SUCBARRANQUILLA { get; set; }
    public string SUCCARTAGENA { get; set; }
    public string SUCBUENAVENTURA { get; set; }
    public string SUCSANTAMARTHA { get; set; }
    public string SUCOTRO { get; set; }
    public string SUCCUAL { get; set; }
    public string CELULAR { get; set; }
    public Nullable<int> DIACIERREFACTURACION { get; set; }
    public Nullable<decimal> IDCIUDADADMINISTRATIVO { get; set; }
    public string CIUDADADMINISTRATIVO { get; set; }
    public string DIRECCIONFACTURACION { get; set; }
    public Nullable<decimal> IDFUNCIONARIO { get; set; }
    public string NOMBREFUNCIONARIO { get; set; }
    public string OBSERVACIONES { get; set; }
    public Nullable<decimal> MONTOAUTORIZADO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIOSWEB> USUARIOSWEB { get; set; }
}

public partial class TIPOCORREOS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPOCORREOS()
    {
        this.CORREOS = new HashSet<CORREOS>();
    }

    public decimal IDTIPOCORREO { get; set; }
    public string TIPOCORREO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CORREOS> CORREOS { get; set; }
}

public partial class TIPORELACIONDOCUMENTOS
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPORELACIONDOCUMENTOS()
    {
        this.RELACIONDOCUMENTOS = new HashSet<RELACIONDOCUMENTOS>();
    }

    public decimal IDTIPORELACIONDOCUMENTO { get; set; }
    public string TIPORELACIONDOCUMENTO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RELACIONDOCUMENTOS> RELACIONDOCUMENTOS { get; set; }
}

public partial class TIPOUSUARIOWEB
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPOUSUARIOWEB()
    {
        this.USUARIOSWEB = new HashSet<USUARIOSWEB>();
    }

    public int IDTIPOUSUARIOWEB { get; set; }
    public string TIPOUSUARIOWEB1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<USUARIOSWEB> USUARIOSWEB { get; set; }
}

public partial class USUARIOSWEB
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USUARIOSWEB()
    {
        this.REFERENCIASPAGOS = new HashSet<REFERENCIASPAGOS>();
    }

    public decimal IDUSUARIOWEB { get; set; }
    public Nullable<decimal> IDTERCERO { get; set; }
    public string PASSWORD { get; set; }
    public string CORREO { get; set; }
    public string CODIGO_ECCARGO { get; set; }
    public Nullable<int> NUMEROINTENTOS { get; set; }
    public Nullable<System.DateTime> FECHACREACION { get; set; }
    public Nullable<bool> ESTADO { get; set; }
    public Nullable<System.DateTime> FECHAULTIMAACTUALIZACION { get; set; }
    public Nullable<int> IDTIPOUSUARIOWEB { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<REFERENCIASPAGOS> REFERENCIASPAGOS { get; set; }
    public virtual TIPOUSUARIOWEB TIPOUSUARIOWEB { get; set; }
    public virtual TERCEROS TERCEROS { get; set; }
}

public partial class v_forward_factitem
{
    public string fac_tipo { get; set; }
    public decimal fac_sucursal { get; set; }
    public decimal fac_numero { get; set; }
    public string fac_comprobante { get; set; }
    public Nullable<decimal> gas_codigo { get; set; }
    public string fac_descripcion1 { get; set; }
    public string fac_descripcion2 { get; set; }
    public string fac_descripcion3 { get; set; }
    public string gas_tipo { get; set; }
    public Nullable<decimal> fac_impneto { get; set; }
    public Nullable<decimal> fac_imptotal { get; set; }
    public Nullable<decimal> fac_numoper { get; set; }
    public Nullable<decimal> fac_posicion { get; set; }
    public string fac_operacion { get; set; }
    public Nullable<bool> fac_agregado { get; set; }
    public Nullable<decimal> pre_numero { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public Nullable<decimal> nro_item { get; set; }
    public Nullable<decimal> fac_sucoper { get; set; }
    public int recno { get; set; }
    public string div_original { get; set; }
    public Nullable<decimal> fac_imporiginal { get; set; }
    public string fac_descripcion4 { get; set; }
    public string fac_descripcion5 { get; set; }
    public Nullable<decimal> fac_impneto2 { get; set; }
    public string con_numero { get; set; }
}

public partial class v_forward_facturas
{
    public string fac_tipo { get; set; }
    public decimal fac_sucursal { get; set; }
    public decimal fac_numero { get; set; }
    public string fac_comprobante { get; set; }
    public Nullable<System.DateTime> fac_fecha { get; set; }
    public string fac_tipocli { get; set; }
    public string fac_cliente { get; set; }
    public string fac_rsocial { get; set; }
    public string div_codigo { get; set; }
    public Nullable<decimal> iva_codigo { get; set; }
    public string fac_condvta { get; set; }
    public Nullable<System.DateTime> fac_fecvto { get; set; }
    public Nullable<decimal> fac_derecho { get; set; }
    public Nullable<decimal> fac_exento { get; set; }
    public Nullable<decimal> fac_gravado { get; set; }
    public Nullable<decimal> fac_iva { get; set; }
    public Nullable<decimal> fac_ivadif { get; set; }
    public Nullable<decimal> fac_subtotal { get; set; }
    public Nullable<decimal> fac_total { get; set; }
    public string fac_detalle1 { get; set; }
    public Nullable<decimal> cot_divlocal { get; set; }
    public Nullable<bool> fac_anulada { get; set; }
    public string fac_remito { get; set; }
    public Nullable<decimal> cot_divotra { get; set; }
    public Nullable<decimal> fac_anticipo { get; set; }
    public string fac_detalle2 { get; set; }
    public string fac_detalle3 { get; set; }
    public string fac_detalle4 { get; set; }
    public string fac_detalle5 { get; set; }
    public Nullable<decimal> fac_difcbiolocal { get; set; }
    public Nullable<decimal> fac_difcbiootra { get; set; }
    public string fac_tipoap { get; set; }
    public Nullable<decimal> fac_sucursalap { get; set; }
    public Nullable<decimal> fac_numeroap { get; set; }
    public string fac_comprobanteap { get; set; }
    public Nullable<System.DateTime> fec_alta { get; set; }
    public string usuario_id { get; set; }
    public Nullable<System.DateTime> fec_pase { get; set; }
    public Nullable<decimal> ots_statnro { get; set; }
    public Nullable<decimal> nro_int { get; set; }
    public Nullable<decimal> fac_paridad { get; set; }
    public Nullable<decimal> fac_sucoper { get; set; }
    public Nullable<bool> fac_CADIVI { get; set; }
    public int Recno { get; set; }
    public string ncf { get; set; }
    public string fac_subgrupo { get; set; }
    public Nullable<decimal> cot_divesp { get; set; }
    public string fac_informacionadic { get; set; }
    public Nullable<decimal> fac_cae { get; set; }
    public Nullable<System.DateTime> fac_vtocae { get; set; }
    public Nullable<decimal> fac_idcae { get; set; }
    public string fac_incoterm { get; set; }
    public Nullable<System.DateTime> fec_anu { get; set; }
    public string anu_usuario_id { get; set; }
    public Nullable<bool> fiscal_anulado { get; set; }
    public string fac_uuid { get; set; }
    public Nullable<decimal> TipoOperacion { get; set; }
    public Nullable<decimal> IDImpositivo { get; set; }
    public string Observaciones { get; set; }
    public string FormaPago { get; set; }
    public string Idioma { get; set; }
    public string fac_tipodeanulacion { get; set; }
    public bool asi_NoafectaNIIF { get; set; }
    public Nullable<bool> permiso_existente { get; set; }
    public string id_permiso_embarque { get; set; }
    public Nullable<decimal> destino_embarque { get; set; }
}
