//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EC_GROUPEntities : DbContext
{
    public EC_GROUPEntities()
        : base("name=EC_GROUPEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<forward_clientes> forward_clientes { get; set; }
    public virtual DbSet<forward_ctacte> forward_ctacte { get; set; }
    public virtual DbSet<forward_factitem> forward_factitem { get; set; }
    public virtual DbSet<forward_facturas> forward_facturas { get; set; }
    public virtual DbSet<forward_recibos> forward_recibos { get; set; }
    public virtual DbSet<INGRESOSPROPIOS> INGRESOSPROPIOS { get; set; }
    public virtual DbSet<REFERENCIASPAGOS> REFERENCIASPAGOS { get; set; }
    public virtual DbSet<RELACIONDOCUMENTOS> RELACIONDOCUMENTOS { get; set; }
    public virtual DbSet<USUARIOSWEB> USUARIOSWEB { get; set; }
    public virtual DbSet<ESTADOSREFERENCIAS> ESTADOSREFERENCIAS { get; set; }
    public virtual DbSet<MONEDAS> MONEDAS { get; set; }
    public virtual DbSet<CORREOS> CORREOS { get; set; }
    public virtual DbSet<TIPOCORREOS> TIPOCORREOS { get; set; }
    public virtual DbSet<TIPOUSUARIOWEB> TIPOUSUARIOWEB { get; set; }
    public virtual DbSet<TIPORELACIONDOCUMENTOS> TIPORELACIONDOCUMENTOS { get; set; }
    public virtual DbSet<CAMBIOSDIVISAS> CAMBIOSDIVISAS { get; set; }
    public virtual DbSet<TERCEROS> TERCEROS { get; set; }
    public virtual DbSet<v_forward_factitem> v_forward_factitem { get; set; }
    public virtual DbSet<v_forward_facturas> v_forward_facturas { get; set; }
    public virtual DbSet<fed_facturas_enviadas> fed_facturas_enviadas { get; set; }
    public virtual DbSet<fed_facturas_no_enviadas> fed_facturas_no_enviadas { get; set; }
    public virtual DbSet<fed_facturas_procesadas> fed_facturas_procesadas { get; set; }
    public virtual DbSet<fed_facturas_procesadas_errores> fed_facturas_procesadas_errores { get; set; }
    public virtual DbSet<fed_parametros> fed_parametros { get; set; }
    public virtual DbSet<fed_resolucion_facturacion> fed_resolucion_facturacion { get; set; }
    public virtual DbSet<fed_usuarios> fed_usuarios { get; set; }
}
